repos:
    - repo: local
      hooks:
          - id: oxlint
            name: oxlint
            entry: pnpm oxlint --fix
            language: system
            types_or: [javascript, jsx, ts, tsx]
            pass_filenames: true

          - id: oxfmt
            name: oxfmt
            entry: pnpm oxfmt
            language: system
            types_or: [javascript, jsx, ts, tsx, json]
            pass_filenames: true

          - id: typecheck
            name: typecheck
            entry: pnpm turbo check
            language: system
            types_or: [ts, tsx]
            pass_filenames: false
